// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppfcwbadvxfgeyaaabhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwZmN3YmFkdnhmZ2V5YWFhYmhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzODU3OTEsImV4cCI6MjA3Mzk2MTc5MX0.lhkrrVFiVw3mYKqH5a7jjMr0FeZVqfs-rout8jDgLqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});